language: ruby
rvm: 
  - 1.9.3
  - 2.0.0
env:
  global:
  - DB=sqlite3
script:
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec/
before_script:
  - cp config/database.travis.yml config/database.yml
